# @name createProduct
POST {{baseUrl}}/products 
Content-Type: application/json

{
  "name": "New Model INSERTED",
  "color": "Black",
  "gas": "electric",
  "year": 2023,
  "description": "New model of year",
  "price": 32000
}

###
@productId = {{createProduct.response.body.$._id}}

PUT {{baseUrl}}/products/{{productId}}
Content-Type: application/json

{
  "name": "New Model UPDATED",
  "color": "Black",
  "gas": "electric",
  "year": 2023,
  "description": "New model of year",
  "price": 32000
}