name: Build the Node.js project
run-name: ${{ github.actor }} is running GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Check Node version
      run: node --version
    - name: Check NPM version
      run: npm --version
    - name: NPM Install
      run: npm install
    - name: NPM Build the solution
      run: npm run build --if-present
